# Tiltfile — local dev loop for http-template.
#
# Companion files:
#   dev/cluster.yaml  — ctlptl-managed kind cluster + local registry
#   dev/traefik.yaml  — Traefik v3 as a Gateway API controller
#   dev/k8s.yaml      — workload + Gateway + HTTPRoutes (BASE_DOMAIN templated)
#
# Inner loop:
#   1. `mise run cluster-up`  (once per machine — also re-run after
#      `rm -rf dev/certs` to rotate the wildcard cert)
#   2. `tilt up`
#   3. Edit Go files. `go-build` recompiles a fresh linux binary at
#      dist/dev/server, live_update sync's it into the running pod and
#      restart_container() bounces the process — no image rebuild for
#      code changes.
#
# Routing topology (kind extraPortMappings publish node 30080/30443
# out to host 80/443):
#
#   http://*.cluster.localhost                  → 301 to https
#   https://apis.cluster.localhost/<app>/*      → <app> backend
#                                                 (gateway strips
#                                                  /<app> prefix)
#   https://traefik.cluster.localhost           → Traefik dashboard
#
# Multi-API gateway pattern: every service mounts under apis.<domain>
# at its own /<name>/* prefix. The Go service stays unaware — it sees
# requests at flat paths like /hello.
#
# Cluster bootstrap (mkcert install, wildcard cert generation, kind
# extraMount of the mkcert root CA into /etc/ssl/certs/, Gateway API
# CRD install, and Secret/cluster-tls creation) all happen in the
# `cluster-up` mise task — Tilt is strictly the inner dev loop here.

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

# Base domain for everything served through the local gateway. Override
# at invocation time with `tilt up -- --base-domain=foo.localhost`.
config.define_string('base-domain')
cfg = config.parse()
BASE_DOMAIN = cfg.get('base-domain', 'cluster.localhost')

# Derive the app name from the Go module path so this template stays
# portable: `gonew github.com/foo/bar` makes APP_NAME=bar with no edits
# to any of the files below. CLUSTER_NAME follows ctlptl's `kind-<name>`
# convention so it matches dev/cluster.yaml.
def _module_basename():
    for line in str(read_file('go.mod')).splitlines():
        line = line.strip()
        if line.startswith('module '):
            return line[len('module '):].strip().split('/')[-1]
    fail('Tiltfile: could not parse module path from go.mod')

APP_NAME = _module_basename()
CLUSTER_NAME = 'kind-' + APP_NAME

# Guard: only ever run against our local kind cluster.
allow_k8s_contexts(CLUSTER_NAME)

default_registry('localhost:5005')

# ---------------------------------------------------------------------
# In-cluster bootstrap (pure Kubernetes — Gateway CRDs + TLS secret)
# ---------------------------------------------------------------------
#
# Raw infra (cluster, node-level mkcert CA trust, wildcard cert files
# on disk) is `mise run cluster-up`'s job. Everything below operates
# against the kube API.

# Gateway API CRDs — pinned, idempotent.
local(
    'kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml',
    quiet=True,
)

# Load the wildcard cert (generated by `mise run cluster-up`) into the
# cluster as a TLS Secret. The `create --dry-run=client | apply` pattern
# is the standard idempotent create-or-update.
local("""
kubectl create secret tls cluster-tls \
  --cert=dev/certs/cluster.pem --key=dev/certs/cluster-key.pem \
  --dry-run=client -o yaml | kubectl apply -f -
""", quiet=True)

# ---------------------------------------------------------------------
# Application build + image
# ---------------------------------------------------------------------

# Native Go compile on the host. Faster than building inside Docker;
# the resulting binary gets sync'd into the container by live_update.
#
# The synchronous local() seed runs at Tiltfile-load time so the
# binary exists on disk before docker_build_with_restart computes its
# build context. The local_resource then handles ongoing rebuilds on
# source changes — Tilt won't sequence local_resource against an
# image build automatically, so we need both.
local('mise run dev-build', quiet=True)
local_resource(
    'go-build',
    cmd='mise run dev-build',
    deps=['cmd', 'internal', 'go.mod', 'go.sum'],
    labels=['app'],
)

load('ext://restart_process', 'docker_build_with_restart')

# Scoping the build context straight to `dist/dev/` sidesteps Tilt's
# gitignore filtering entirely — the gitignored `dist/` prefix lives
# above the context root, so buildkit never has to reason about it,
# and `dist/` stays cleanly gitignored at the project level.
#
# docker_build_with_restart injects RUN touch/chmod + COPY steps for
# its tilt-restart-wrapper, so the base image needs a shell and
# coreutils at *build* time. That rules out distroless here — we use
# alpine for the dev image. Production still goes through goreleaser
# → distroless; this divergence only affects the Tilt inner loop.
# On every live_update Tilt touches /tmp/.restart-proc and the wrapper
# re-execs `/server` against the synced binary, replacing the
# deprecated `restart_container()` step.
docker_build_with_restart(
    APP_NAME,
    context='dist/dev',
    entrypoint='/server',
    dockerfile_contents='''
FROM alpine:3.20
COPY server /server
EXPOSE 8080
ENTRYPOINT ["/server"]
''',
    live_update=[
        sync('dist/dev/server', '/server'),
    ],
)

# ---------------------------------------------------------------------
# Manifests
# ---------------------------------------------------------------------

# Traefik install — static, no templating needed.
k8s_yaml('dev/traefik.yaml')

# Workload + Gateway + HTTPRoutes — render ${BASE_DOMAIN} and ${APP_NAME}
# into the file. Pure in-memory string substitution: read_file() returns
# the contents and blob() hands the rendered string straight to k8s_yaml,
# so dev/k8s.yaml on disk is never touched and stays valid YAML for
# editor/lint tooling. Same envsubst-style ${VAR} convention as
# dev/cluster.yaml.
manifest = str(read_file('dev/k8s.yaml'))
manifest = manifest.replace('${BASE_DOMAIN}', BASE_DOMAIN)
manifest = manifest.replace('${APP_NAME}', APP_NAME)
k8s_yaml(blob(manifest))

# ---------------------------------------------------------------------
# Resource wiring
# ---------------------------------------------------------------------

k8s_resource(
    'traefik',
    labels=['gateway'],
    # No port_forwards — kind extraPortMappings already publishes
    # NodePort 30080/30443 to host 80/443.
)

# Bundle the Gateway API control-plane objects (RBAC + GatewayClass +
# Gateway + the two infra HTTPRoutes) into a single Tilt resource so
# they show up under the `gateway` label instead of landing in the
# default uncategorized bucket.
k8s_resource(
    objects=[
        'traefik:serviceaccount',
        'traefik-gateway:clusterrole',
        'traefik-gateway:clusterrolebinding',
        'traefik:gatewayclass',
        'gateway:gateway',
        'redirect-to-https:httproute',
        'traefik-dashboard:httproute',
    ],
    new_name='gateway-config',
    labels=['gateway'],
)

k8s_resource(
    APP_NAME,
    objects=[APP_NAME + ':httproute'],
    resource_deps=['go-build', 'traefik'],
    labels=['app'],
    links=[
        link('https://apis.{}/{}/hello'.format(BASE_DOMAIN, APP_NAME), 'hello'),
        link('https://traefik.{}'.format(BASE_DOMAIN), 'traefik dashboard'),
    ],
)
